#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-estilo-visual-iconos-gnome
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Sasha Veronica Solano Grosjean <sashasolano@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
if [ -f /usr/share/applications/yelp.desktop ];
  then
    echo "Eliminando archivo yelp.desktop"
    rm -f /usr/share/applications/yelp.desktop
  fi
  exit 0

