#! /bin/sh
set -e

if [ "$1" = "configure" ]; then

  if [ -f /etc/skel/Escritorio/ayuda.desktop ];
  then
    echo "Eliminando archivo obsoleto de ayuda"
    rm -f /etc/skel/Escritorio/ayuda.desktop
  fi
  exit 0

fi


